### ISSUE TITLE
Kontroller

### ISSUE THREAD

**Issue by wizofwor** [vigo/dinozorus#1]
Yıllar sonra Dinozorus'un kendi bilgisayarlarımızda çalıştığını görmek çok güzel ama oyunun kontrollerini çözemedik. Acaba telefona bağlanan özel bir aparat mı lazım yoksa kontroller klavyeye mi bağlı?

**Comment by vigo** [comment]
normal joystick ile oynanıyor. keza emülatör'den de klavye ile oynanabiliyor. adf'leri hazırlıyorum direk boot edilebilecek...

**Comment by ozayturay** [comment]
Abi ben hazırladım bile ADF, facebook'da LW3D'nin duyurusunda yazmıştım ama buraya da linkleyeyim. :)

Amiga ADF: https://dl.dropboxusercontent.com/u/18575245/%23CGTr/Dinozorus.adf.zip

Windows EXE: https://dl.dropboxusercontent.com/u/18575245/%23CGTr/Dinozorus.exe.zip
