### ISSUE TITLE
RAM Gereksinimi

### ISSUE THREAD

**Issue by ozayturay** [vigo/dinozorus#2]
Emülatörde 2MB standart Amiga 1200 ile çalışmıyor, Startup-Sequence ve User-Startup dosyasından yüklenen birşeyler yüzünden olabilir mi?
## DF0: İçeriği:

DF0:\C
DF0:\C.info
DF0:\C\Assign
DF0:\C\Execute
DF0:\C\Pause
DF0:\Dinozorus
DF0:\Dinozorus.info
DF0:\Dinozorus\dinozorus-level1.exe
DF0:\Dinozorus\dinozorus-level1.exe.info
DF0:\S
DF0:\S.info
DF0:\S\Startup-Sequence
DF0:\S\User-Startup
## Startup-Sequence:

C:Assign >NIL: ENV: RAM:
C:Assign >NIL: T: RAM:
FailAt 21
If Exists S:User-Startup
  Execute S:User-Startup
EndIf
## User-Startup:

echo ""
echo "Dinozorus TV Game"
echo ""
echo "Code: Ugur 'vigo' Ozyilmazel"
echo "Supervisor: Huseyin 'ghost' Yesilbas"
echo "Music: Tolga 'max' Meric"
echo "Graphics: Sahin Erkocak"
echo "Music playing routine PRORUNNER"
echo ""
echo "EXE Conversion: Ozay 'Simon' Turay"
echo "Dedicated to fellow friends at CGTr"
echo "http://www.commodore.gen.tr"

echo ""
echo "Press ENTER to begin loading"
C:Pause >NIL:

cd Dinozorus

echo ""
echo "Loading Dinozorus - Level 1..."
echo ""
dinozorus-level1.exe

**Comment by vigo** [comment]
Fast Memory de lazım en az 2. Keza ben official adf üzerinde çalışıyorum, GitHub'a koyacağım, ricam şu ki kafanıza göre release yapmayın. 1-2 gün daha sabır :)

**Comment by ozayturay** [comment]
Cevap için teşekkürler.

Official release olacaksa ben kaldırıyorum benim yaptıklarımı o halde. Umarım diğer bölümler ve data dosyaları da çıkar ortaya. :)
