### ISSUE TITLE
Game not working on FS-UAE-Launcher

### ISSUE THREAD

**Issue by yasinaydinnet** [vigo/dinozorus#4]
I am using https://fs-uae.net/launcher on Arch Linux with default settings. I have Amiga 1200 3.1 (40.068) Kickstart installed. I can run some other games but when I load 2 disks in ADF folder the game won't start. 

@denizkanmaz Also had the same problem.

Any ideas?

**Comment by wizofwor** [comment]
Do you have fastmem? It doesn't work with 2MB.

**Comment by yasinaydinnet** [comment]
I was using default settings. 
Should I override anything here? 
![image](https://user-images.githubusercontent.com/1379677/85271115-0b359d80-b483-11ea-977d-b8d99eb52e2c.png)

PS: The error is this:
![image](https://user-images.githubusercontent.com/1379677/85271318-4f28a280-b483-11ea-8956-5d3013e242cb.png)

**Comment by denizkanmaz** [comment]
Hi @wizofwor 
It seems the current adf in the repo is not bootable. Tried with emulator by using a regular A1200 configuration such as 68020 + 4MB Fast Ram Expansion + Kickstart 3.1 (40.063). Gunship 2000 AGA works with the same configuration.

I am sharing the WinUAE (4.3.0 x64) configuration file below.
[game-aga-dinozorus.zip](https://github.com/vigo/dinozorus/files/4817448/game-aga-dinozorus.zip)

**Comment by ref-xx** [comment]
@yasinaydinnet, as @denizkanmaz said, disks are not bootable. You may use any workbench disk to make them bootable. Just boot into 2.1+ version of workbench (insert the dinozoruz game disk into *DF1:*, *before* booting the emulator) , open CLI or Shell, and type: 
`INSTALL DF1:` 
 it will take a a second or two and the disk will be bootable.

also, @denizkanmaz , you are using wrong version of kickstart rom. You should switch to 32bit version with 020. You are using rom3.1 made for 16bit 68k processors (40.063). You should switch it with 40.068 or above to avoid guru meditations and lockups.

**Comment by vigo** [comment]
Sorry, I'm super busy lately. I'll check @ref-xx 's PR + will try to kick via fs-uae (which I use mac too)
